[build]
  publish = "dist"                   # Folder to deploy (Vite build output)
  command = "npm run build"          # Build command

[build.environment]
  NODE_VERSION = "18"                # Node version for build

# SPA routing - handle all routes by redirecting to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Redirect API calls to your backend
[[redirects]]
  from = "/api/*"
  to = "https://fashionfusion-g78z.onrender.com/api/:splat"
  status = 200
  force = true

# Environment variables for production
[context.production.environment]
  VITE_API_BASE_URL = "https://fashionfusion-g78z.onrender.com/api"

# Environment variables for deploy preview (PR builds)
[context.deploy-preview.environment]
  VITE_API_BASE_URL = "https://fashionfusion-g78z.onrender.com/api"

# Environment variables for branch deploys
[context.branch-deploy.environment]
  VITE_API_BASE_URL = "https://fashionfusion-g78z.onrender.com/api"


